Fix spelling of several words in user-facing text & logs
stoped -> stopped
stoping -> stopping
uppgrade -> upgrade
dowloading -> downloading
ouput -> output
lastest -> latest
Openvidu -> OpenVidu

diff --git a/openvidu-server/deployments/ce/aws/CF-OpenVidu.yaml.template b/openvidu-server/deployments/ce/aws/CF-OpenVidu.yaml.template
--- a/openvidu-server/deployments/ce/aws/CF-OpenVidu.yaml.template
+++ b/openvidu-server/deployments/ce/aws/CF-OpenVidu.yaml.template
@@ -100,7 +100,7 @@ Parameters:
   # Other configuration
 
   WantToDeployDemos:
-    Description: "Choose if you want to deploy OpenVidu Call application alongside OpenVidu platform." 
+    Description: "Choose if you want to deploy OpenVidu Call application alongside OpenVidu platform."
     Type: String
     AllowedValues:
       - true
@@ -180,7 +180,7 @@ Metadata:
 Conditions:
     WhichCertPresent: !Not [ !Equals [!Ref WhichCert, ""] ]
     PublicElasticIPPresent: !Not [ !Equals [!Ref PublicElasticIP, ""] ]
-    
+
 Resources:
 
   OpenviduServer:
@@ -224,7 +224,7 @@ Resources:
               content: !Sub |
                 #!/bin/bash -x
                 WORKINGDIR=/opt/openvidu
-                
+
                 # Replace secret
                 sed -i "s/OPENVIDU_SECRET=/OPENVIDU_SECRET=${OpenViduSecret}/" $WORKINGDIR/.env
 
@@ -243,7 +243,7 @@ Resources:
                 # Replace certificated type
                 sed -i "s/CERTIFICATE_TYPE=selfsigned/CERTIFICATE_TYPE=${WhichCert}/" $WORKINGDIR/.env
                 sed -i "s/LETSENCRYPT_EMAIL=user@example.com/LETSENCRYPT_EMAIL=${LetsEncryptEmail}/" $WORKINGDIR/.env
-                
+
                 # Without Application
                 if [ "${WantToDeployDemos}" == "false" ]; then
                   sed -i "s/WITH_APP=true/WITH_APP=false/" $WORKINGDIR/docker-compose.yml
@@ -265,7 +265,7 @@ Resources:
               content: !Sub |
                 #!/bin/bash -x
                 WORKINGDIR=/opt/openvidu
-                
+
                 # Get new amazon URL
                 OldPublicHostname=$(cat /usr/share/openvidu/old-host-name)
                 PublicHostname=$(curl http://169.254.169.254/latest/meta-data/public-hostname)
@@ -302,14 +302,14 @@ Resources:
           export HOME="/root"
 
           # Replace .env variables
-          /usr/local/bin/feedGroupVars.sh || { echo "[Openvidu] Parameters incorrect/insufficient"; exit 1; }
+          /usr/local/bin/feedGroupVars.sh || { echo "[OpenVidu] Parameters incorrect/insufficient"; exit 1; }
 
           # Launch on reboot
           echo "@reboot /usr/local/bin/restartCE.sh" | crontab
 
           # Download certs if "WichCert" mode
           if [ "${WhichCert}" == "owncert" ]; then
-            /usr/local/bin/buildCerts.sh || { echo "[Openvidu] error with the certificate files"; exit 1; }
+            /usr/local/bin/buildCerts.sh || { echo "[OpenVidu] error with the certificate files"; exit 1; }
           fi
 
           # Start openvidu application
@@ -325,13 +325,13 @@ Resources:
           if [ "${WantToSendInfo}" == "true" ]; then
             /usr/local/bin/ping.sh || true
           fi
-          rm /usr/local/bin/ping.sh 
+          rm /usr/local/bin/ping.sh
 
           # Wait for the app
           /usr/local/bin/check_app_ready.sh
 
           # Start up the cfn-hup daemon to listen for changes to the Web Server metadata
-          /usr/local/bin/cfn-hup -v || { echo "[Openvidu] Failed to start cfn-hup"; exit 1; }
+          /usr/local/bin/cfn-hup -v || { echo "[OpenVidu] Failed to start cfn-hup"; exit 1; }
 
           # sending the finish call
           /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WaitCondition --region ${AWS::Region}
diff --git a/openvidu-server/deployments/pro/aws/cfn-openvidu-server-pro-no-market.yaml.template b/openvidu-server/deployments/pro/aws/cfn-openvidu-server-pro-no-market.yaml.template
--- a/openvidu-server/deployments/pro/aws/cfn-openvidu-server-pro-no-market.yaml.template
+++ b/openvidu-server/deployments/pro/aws/cfn-openvidu-server-pro-no-market.yaml.template
@@ -1,6 +1,6 @@
 ---
 AWSTemplateFormatVersion: 2010-09-09
-Description: Openvidu Pro CloudFormation template
+Description: OpenVidu Pro CloudFormation template
 
 Parameters:
 
@@ -41,11 +41,11 @@ Parameters:
   LetsEncryptEmail:
     Description: "If certificate type is 'letsencrypt', this email will be used for Let's Encrypt notifications"
     Type: String
-  
+
   Recording:
     Description: |
       If 'disabled', recordings will not be active.
-      If 'local' recordings will be saved in EC2 instance locally. 
+      If 'local' recordings will be saved in EC2 instance locally.
       If 's3', recordings will be stored in a S3 bucket"
     Type: String
     AllowedValues:
@@ -328,15 +328,15 @@ Conditions:
   CreateS3Bucket: !And
     - !Equals [!Ref Recording, 's3' ]
     - !Equals [!Ref S3RecordingsBucketName, '']
-        
+
 Rules:
 
   RecordingValidation:
-    RuleCondition: 
+    RuleCondition:
       Fn::Or: [ !Equals [!Ref Recording, 'disabled' ], !Equals [!Ref Recording, 'local' ] ]
     Assertions:
       - AssertDescription: If recording Storage is 'disabled' or 'local', you don't need to specify a S3 bucket.
-        Assert: 
+        Assert:
           Fn::Equals: [ !Ref S3RecordingsBucketName, "" ]
 
 Resources:
@@ -380,7 +380,7 @@ Resources:
                     - 's3:DeleteObject'
                     - 's3:GetObject'
                     - 's3:PutObject'
-                  Resource: 
+                  Resource:
                     - Fn::If:
                       # Get bucket name depending if the user defines a bucket name or not
                       - CreateS3Bucket
@@ -392,10 +392,10 @@ Resources:
                 # Only apply this policy if S3 is configured
                 - RecordingStorageIsS3
                 - Effect: Allow
-                  Action: 
+                  Action:
                     - 's3:ListBucket'
                     - 's3:GetBucketLocation'
-                  Resource: 
+                  Resource:
                     - Fn::If:
                       # Get bucket name depending if the user defines a bucket name or not
                       - CreateS3Bucket
@@ -429,7 +429,7 @@ Resources:
     ### Unique bucket name using Stack ID
       BucketName: !Join ["-" , [ 'openvidu-recordings', !Select [0, !Split ["-", !Select [2, !Split [/, !Ref AWS::StackId ]]]]]]
       AccessControl: Private
-      PublicAccessBlockConfiguration: 
+      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls : true
@@ -483,13 +483,13 @@ Resources:
                   echo $PublicHostname > /usr/share/openvidu/old-host-name
                 fi
 
-                # Openvidu Pro mode
+                # OpenVidu Pro mode
                 sed -i "s/OPENVIDU_PRO_CLUSTER_MODE=manual/OPENVIDU_PRO_CLUSTER_MODE=auto/" $WORKINGDIR/.env
 
-                # Openvidu Pro Media Nodes
+                # OpenVidu Pro Media Nodes
                 sed -i "s/#OPENVIDU_PRO_CLUSTER_MEDIA_NODES=/OPENVIDU_PRO_CLUSTER_MEDIA_NODES=${MediaNodesStartNumber}/" $WORKINGDIR/.env
 
-                # Openvidu Pro enviroment
+                # OpenVidu Pro enviroment
                 sed -i "s/OPENVIDU_PRO_CLUSTER_ENVIRONMENT=on_premise/OPENVIDU_PRO_CLUSTER_ENVIRONMENT=aws/" $WORKINGDIR/.env
 
                 # Replace certificated type
@@ -650,17 +650,17 @@ Resources:
             export HOME="/root"
 
             # Replace .env variables
-            /usr/local/bin/feedGroupVars.sh || { echo "[Openvidu] Parameters incorrect/insufficient"; exit 1; }
+            /usr/local/bin/feedGroupVars.sh || { echo "[OpenVidu] Parameters incorrect/insufficient"; exit 1; }
 
             # Create security groups
-            /usr/local/bin/create_security_group_rules.sh || { echo "[Openvidu] Error creating security groups"; exit 1; }
+            /usr/local/bin/create_security_group_rules.sh || { echo "[OpenVidu] Error creating security groups"; exit 1; }
 
             # Launch on reboot
             echo "@reboot /usr/local/bin/restartPRO.sh" | crontab
 
             # Download certs if "WichCert" mode
             if [ "${WhichCert}" == "owncert" ]; then
-              /usr/local/bin/buildCerts.sh || { echo "[Openvidu] error with the certificate files"; exit 1; }
+              /usr/local/bin/buildCerts.sh || { echo "[OpenVidu] error with the certificate files"; exit 1; }
             fi
 
             # Start openvidu application
